/** Shared Pino redact paths for API HTTP and worker logs. Never log secrets or direct identifiers. */
export const PINO_REDACT_PATHS = [
  'req.headers.authorization',
  'req.headers.cookie',
  'res.headers["set-cookie"]',
  'req.body.password',
  'req.body.newPassword',
  'req.body.currentPassword',
  'req.body.temporaryPassword',
  'req.body.refreshToken',
  'req.body.token',
  'req.body.cardToken',
  'req.body.client_secret',
  'req.body.documentNumber',
  'req.body.cpfCnpj',
  'req.body.phone',
  'req.body.whatsapp',
  'req.body.email',
  'req.body.customFieldValues',
  'req.body.address',
  'req.body.postalCode',
  'req.body.ip',
  'req.query.token',
  'req.query.webhookSecret',
  'req.query.secret',
  'req.query.email',
  'req.headers["x-prospectly-ops-token"]',
  'req.headers["x-abacate-webhook-secret"]',
  'req.headers["x-webhook-secret"]',
  'req.headers["asaas-access-token"]',
  '*.password',
  '*.newPassword',
  '*.currentPassword',
  '*.refreshToken',
  '*.accessToken',
  '*.authorization',
  '*.cookie',
  '*.cpfCnpj',
  '*.documentNumber',
  '*.customFieldValues',
  '*.address',
  '*.postalCode',
  '*.apiKey',
  '*.api_key',
  '*.client_secret',
] as const;

export const PINO_REDACT_CENSOR = '[REDACTED]';
