#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=11

CANONICAL_API_HOST_DEFAULT="api.prospectlyonboard.com"
APP_ORIGIN="https://app.prospectlyonboard.com"
LANDING_ORIGIN="https://prospectlyonboard.com"
LEGACY_API_HOST="prospectly-api.onrender.com"
RENDER_API_DASHBOARD="https://dashboard.render.com/web/srv-da2dbqugekts73b4ma40"
RENDER_WEB_DASHBOARD="https://dashboard.render.com/web/srv-da2dc16gekts73b4mtlg"
RENDER_LANDING_DASHBOARD="https://dashboard.render.com/web/srv-d9ql5njm8hqs738m8bu0"
GOOGLE_CREDENTIALS_URL="https://console.cloud.google.com/apis/credentials"
NAMECHEAP_DNS_URL="https://ap.www.namecheap.com/Domains/DomainControlPanel/prospectlyonboard.com/domain/advancedns"
RENDER_CUSTOM_DOMAINS_DOCS="https://render.com/docs/custom-domains"
OAUTH_CALLBACK_PATH="/api/v1/google-connections/callback"
ASAAS_WEBHOOK_PATH="/api/v1/billing/webhook/asaas"

probe_api_health() {
  local host="$1"
  if ! command -v curl >/dev/null 2>&1; then
    warn "curl ausente; verifica no browser: https://${host}/health/ready"
    return 1
  fi
  curl -fsS --max-time 20 "https://${host}/health/ready"
}

banner "API em domínio próprio — Prospectly (#179)"

# Issue #179 ticket 1: DNS/TLS/OAuth/env. Não inventar nem gravar secrets.
# Não write_env / ask_secret / set_secret de chaves Google, JWT ou Asaas.
# SameSite=lax só depois do app falar com o host novo (SEC-001).

stage "Regras — cutover sem partir sessão"
say "Este wizard não grava chaves. Segredos ficam no Render Dashboard. Nada na issue #179."
step "Não ligues https://api.asaas.com/v3 (produção Asaas está fora desta spec)."
step "Não mudes o domínio do app (app.prospectlyonboard.com já é canónico)."
step "Não definas Domain=.onrender.com no cookie de refresh (public suffix)."
step "Não ponhas REFRESH_COOKIE_SAME_SITE=lax enquanto VITE_API_URL ainda apontar para ${LEGACY_API_HOST} — o browser deixa de enviar o cookie (cross-site)."
step "CORS sem *. Lista explícita: app + landing."
open_url "https://github.com/Gleydsong/prospectly/issues/179"
pause "Li as regras. Continuar?"

stage "Host canónico"
say "Proposta da spec: ${CANONICAL_API_HOST_DEFAULT} (CNAME para o serviço Render prospectly-api)."
ask CANONICAL_API_HOST "Host da API sem https (Enter = ${CANONICAL_API_HOST_DEFAULT}):"
CANONICAL_API_HOST="${CANONICAL_API_HOST:-$CANONICAL_API_HOST_DEFAULT}"
API_ORIGIN="https://${CANONICAL_API_HOST}"
NEW_OAUTH_REDIRECT="${API_ORIGIN}${OAUTH_CALLBACK_PATH}"
LEGACY_OAUTH_REDIRECT="https://${LEGACY_API_HOST}${OAUTH_CALLBACK_PATH}"
NEW_ASAAS_WEBHOOK="${API_ORIGIN}${ASAAS_WEBHOOK_PATH}"
LEGACY_ASAAS_WEBHOOK="https://${LEGACY_API_HOST}${ASAAS_WEBHOOK_PATH}"
say "Host desta corrida: ${CANONICAL_API_HOST}"
note "App continua ${APP_ORIGIN}. Worker continua interno (sem custom domain)."
pause "Host confirmado?"

stage "Render — Custom Domain"
say "O plugin da Render não cria custom domains. Adiciona o host no serviço da API."
open_url "$RENDER_CUSTOM_DOMAINS_DOCS"
open_url "$RENDER_API_DASHBOARD"
step "prospectly-api → Settings → Custom Domains → Add ${CANONICAL_API_HOST}."
step "Copia o alvo CNAME que a Render mostrar (em geral ${LEGACY_API_HOST})."
pause "Custom domain adicionado no serviço da API?"

stage "Namecheap — CNAME"
say "DNS do prospectlyonboard.com. App já tem CNAME app → prospectly-web.onrender.com; este passo é só o host api."
open_url "$NAMECHEAP_DNS_URL"
step "Domain List → Manage prospectlyonboard.com → Advanced DNS."
step "Tipo CNAME, Host api, Valor ${LEGACY_API_HOST}. (ou o hostname exacto que a Render mostrou)."
step "TTL 1 min enquanto valida; depois Automatic. Sem AAAA neste host."
step "Não apagues o CNAME de app nem os records da landing (@ / www)."
pause "CNAME api gravado no Namecheap?"

stage "TLS Render + health"
say "A Render emite o certificado depois do CNAME resolver. Ticket 2 (código no repo) só desbloqueia com health 200 neste host."
open_url "$RENDER_API_DASHBOARD"
step "Espera o estado do custom domain ficar Verified + TLS."
step "Não mudes ainda VITE_API_URL nem SameSite."
if probe_api_health "$CANONICAL_API_HOST" >/dev/null; then
  say "Probe: https://${CANONICAL_API_HOST}/health/ready respondeu."
else
  warn "Ainda não há TLS/DNS. Re-corre este wizard depois do certificado. Código CORS/cookie no git continua bloqueado."
  SKIPPED+=("https://${CANONICAL_API_HOST}/health/ready")
fi
pause "Certificado no ar (ou anotaste que ainda falta)?"

stage "Google Cloud — redirect overlap"
say "Conexão Google (Gmail/Calendar) usa redirect_uri exacto. Sign-In GIS usa JavaScript origin do app — não muda."
say "Env da API só tem UM GOOGLE_OAUTH_REDIRECT_URI. O Console precisa dos DOIS URIs no overlap."
open_url "$GOOGLE_CREDENTIALS_URL"
step "APIs & Services → Credentials → o OAuth 2.0 Client Web (o mesmo de GOOGLE_CLIENT_ID)."
step "Authorized redirect URIs: adiciona ${NEW_OAUTH_REDIRECT}"
step "Overlap: ${LEGACY_OAUTH_REDIRECT} só até o ticket 3. Depois fica só ${NEW_OAUTH_REDIRECT}."
step "Authorized JavaScript origins: ${APP_ORIGIN} (já deve existir). Não uses *."
step "GOOGLE_CLIENT_ID / GOOGLE_CLIENT_SECRET: abre o valor no Render, tira newline no fim (já quebrou OAuth). Não coloques a chave neste terminal."
warn "invalid_client = Client ID/secret/origem. invalid_grant = código/refresh. São erros diferentes."
pause "URI novo no Console e URI velho ainda lá?"

stage "Render env — só depois do health 200"
say "SEC-001: API + web no mesmo cutover. Lax no cookie só quando o browser fala com ${API_ORIGIN}."
open_url "$RENDER_API_DASHBOARD"
step "prospectly-api → Environment. Não cola secrets aqui. Valores públicos a colar:"
note "FRONTEND_URL=${APP_ORIGIN}"
note "CORS_ORIGINS=${APP_ORIGIN},${LANDING_ORIGIN},https://www.prospectlyonboard.com"
note "GOOGLE_OAUTH_REDIRECT_URI=${NEW_OAUTH_REDIRECT}"
note "REFRESH_COOKIE_SAME_SITE=lax  ← só nesta janela, com o web já a apontar para o host novo"
open_url "$RENDER_WEB_DASHBOARD"
step "prospectly-web → Environment → VITE_API_URL=${API_ORIGIN}/api/v1  (rebuild; VITE_* é build-time)"
open_url "$RENDER_LANDING_DASHBOARD"
step "prospectly-landing → NEXT_PUBLIC_API_URL=${API_ORIGIN}/api/v1  (rebuild)"
step "prospectly-worker: se tiver GOOGLE_OAUTH_REDIRECT_URI, o mesmo valor da API. Worker sem custom domain."
step "Strip newline em GOOGLE_CLIENT_ID e GOOGLE_CLIENT_SECRET depois de colar."
if confirm "https://${CANONICAL_API_HOST}/health/ready já devolve 200?"; then
  pause "Envs colados no Dashboard e redesploy API+web(+landing) disparados?"
else
  warn "Não actualizes VITE_API_URL nem SameSite=lax ainda."
  SKIPPED+=("Render env cutover (espera TLS)")
  pause "Percebi: env de cutover fica para a próxima corrida?"
fi

stage "Asaas Sandbox — webhook URL"
say "Inbound. Produção Asaas continua desligada. Não uses api.asaas.com."
note "URL nova: ${NEW_ASAAS_WEBHOOK}"
note "URL actual (overlap): ${LEGACY_ASAAS_WEBHOOK}"
open_url "https://sandbox.asaas.com/"
step "Sandbox → Integrações → Webhooks."
step "Overlap: webhook extra na URL nova (mesmo ASAAS_WEBHOOK_TOKEN). Ticket 3 apaga o webhook onrender."
step "Header asaas-access-token. Eventos PAYMENT_* iguais aos de agora."
step "Não coloques o token neste wizard."
pause "Webhook novo criado (ou anotaste que o health ainda bloqueia)?"

stage "Probe + overlap"
say "Depois do DNS: health, CORS do app, login cookie, Conexão Google."
step "curl -i https://${CANONICAL_API_HOST}/health/ready"
step "Preflight: Origin ${APP_ORIGIN} → Access-Control-Allow-Origin exactamente essa origem, credentials true."
step "Login no app: cookie Host-only, Secure, SameSite=Lax, path /api/v1/auth. Sem Domain=."
step "Ligar Google: callback no host novo. Se falhar, distingue invalid_grant ≠ invalid_client."
step "Playwright (skip se o CNAME não resolver): pnpm --filter @prospectly/web exec playwright test --config playwright.probe.config.ts"
step "Overlap: ${LEGACY_API_HOST} fica no ar até o ticket 3. Não desligues o Render Subdomain neste passo."
if probe_api_health "$CANONICAL_API_HOST"; then
  say "Health no host novo OK."
else
  warn "Probe ainda falha — ticket 1 não está fechado; ticket 2 continua bloqueado."
  SKIPPED+=("probe ${CANONICAL_API_HOST}")
fi
pause "Probes feitos ou adiados até o CNAME responder?"

stage "Ticket 3 — overlap fechado"
say "Só depois do app estável no host novo (login + Conexão Google). Rollback: reactivar Render Subdomain."
open_url "$GOOGLE_CREDENTIALS_URL"
step "Google Console: apaga ${LEGACY_OAUTH_REDIRECT}. Fica só ${NEW_OAUTH_REDIRECT}."
step "Não apagues origem JS ${APP_ORIGIN} nem http://localhost:5173."
open_url "https://sandbox.asaas.com/"
step "Asaas sandbox: apaga o webhook cuja URL é ${LEGACY_ASAAS_WEBHOOK}. Fica ${NEW_ASAAS_WEBHOOK}."
open_url "$RENDER_API_DASHBOARD"
step "prospectly-api → Settings → Custom Domains → Render Subdomain → Disabled (sudo no Dashboard). Só a API, não o web."
step "curl -i https://${LEGACY_API_HOST}/health/ready → 404 + x-render-routing: blocked-render-subdomain (sem redirect)."
step "curl -i https://${CANONICAL_API_HOST}/health/ready → 200."
pause "Overlap fechado (ou ainda no overlap de propósito)?"

stage "Fora desta spec"
step "Não ligar api.asaas.com."
step "Não Microsoft/MCP."
step "Não mudar o domínio do app."
step "Não feature flags por org."
step "Não desligar o onrender do web (prospectly-web)."
warn "Issue #179 fecha quando o ticket 3 estiver verificado (onrender 404, app no host novo)."
pause "Wizard concluído (DNS humano; sem secrets neste repo)?"

finish
