#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=12

banner "Asaas Sandbox — homologação Prospectly (#81)"

# Issue #81: document credentials and webhook without inventing or persisting secrets.
# Do not write_env / ask_secret / set_secret for ASAAS_API_KEY or ASAAS_WEBHOOK_TOKEN.

stage "Regras — só Sandbox"
say "Este wizard não grava chaves. Segredos vão só para o Render Dashboard (ou .env local teu)."
step "Nunca uses https://api.asaas.com/v3 neste roteiro."
step "Nunca coloques PAN, validade ou CVV no Prospectly — só na Fatura/Checkout hospedado Asaas."
step "Cartões: só números fictícios. Recusa: Mastercard 5184019740373151 ou Visa 4916561358240741."
open_url "https://docs.asaas.com/docs/sandbox-2"
pause "Li as regras. Continuar?"

stage "Conta Sandbox"
say "Conta Sandbox é independente da produção."
open_url "https://sandbox.asaas.com/"
step "Cria ou entra na conta Sandbox (não a conta live)."
step "Completa os dados comerciais se o Asaas pedir aprovação automática."
pause "Conta Sandbox aberta?"

stage "API Key Sandbox"
say "A chave de Sandbox começa tipicamente com \$aact_hmlg_ . Não cole aqui."
open_url "https://sandbox.asaas.com/"
step "No Sandbox Asaas: Integrações → gerar API Key deste ambiente."
step "Render → prospectly-api → Environment → cola em ASAAS_API_KEY (sync: false)."
step "Confirma ASAAS_API_BASE_URL = https://api-sandbox.asaas.com/v3"
open_url "https://dashboard.render.com/web/srv-da2dbqugekts73b4ma40"
pause "ASAAS_API_KEY está no Render, não neste wizard?"

stage "Webhook Sandbox"
say "URL pública da API: https://api.prospectlyonboard.com/api/v1/billing/webhook/asaas"
open_url "https://docs.asaas.com/docs/criar-novo-webhook-pela-aplicacao-web"
step "Sandbox Asaas: menu do utilizador → Integrações → Webhooks → Criar Webhook."
step "URL: https://api.prospectlyonboard.com/api/v1/billing/webhook/asaas"
step "Auth Token: clica Gerar token (32–255 chars, sem espaços). NÃO uses a API Key como token."
step "O mesmo valor vai para Render ASAAS_WEBHOOK_TOKEN. Header esperado: asaas-access-token"
step "Eventos: PAYMENT_CONFIRMED, PAYMENT_RECEIVED, PAYMENT_REFUNDED, PAYMENT_CHARGEBACK_REQUESTED e restantes PAYMENT_CHARGEBACK*."
step "Enabled = sim. Resposta 2xx só depois de persistir o evento (já é o comportamento da API)."
pause "Webhook criado e token igual no Render?"

stage "Flags — não ligar produção"
say "Código: ASAAS_ENABLED só fica true se a env for exatamente 'true'. Unset = false."
say "Cutover PIX autorizado já usa ASAAS_ENABLED=true + URL Sandbox no render.yaml."
step "Não mudes ASAAS_API_BASE_URL para https://api.asaas.com/v3 sem autorização humana + smoke."
step "Rollback PIX: PIX_PROVIDER=DISABLED, sem fallback silencioso."
pause "Produção Asaas continua desligada neste roteiro?"

stage "Perfil de cobrança (#76)"
say "App: Créditos / settings de billing. Só OWNER/ADMIN editam."
open_url "https://app.prospectlyonboard.com"
step "Como OWNER/ADMIN: preenche razão social, CPF/CNPJ, telefone, e-mail, morada."
step "Como SALES/VIEWER: PUT /billing/profile deve 403."
step "Confirma que o cliente Asaas (cus_…) reutiliza na segunda gravação."
pause "Perfil gravado sem dados de cartão?"

stage "Pacote cartão de crédito (#77)"
say "Pacotes 2.000 (R$ 14,99) e 5.000 (R$ 23,99). Pix continua Asaas PIX; cartão = Fatura hospedada."
step "Em Créditos, compra um pacote com «Cartão de crédito ou débito»."
step "Redireciona para invoiceUrl Asaas. Paga com cartão fictício válido (CCV 123, validade futura)."
step "Espera webhook PAYMENT_CONFIRMED e créditos na org. Replay do mesmo evento não duplica saldo."
pause "Pacote crédito confirmado uma vez?"

stage "Pacote débito hospedado (#77)"
say "Débito não vai na API. Só na invoiceUrl (billingType CREDIT_CARD ou UNDEFINED)."
step "Outro pacote → Fatura Asaas → escolhe débito na página hospedada, se o Sandbox mostrar a opção."
step "Se o Sandbox não listar débito nesta conta, regista a restrição e não inventes captura transparente."
pause "Débito hospedado tentado (ou restrição anotada)?"

stage "Mensal recorrente no cartão (#79)"
say "Acesso mensal R$ 49,99: Pix 30 dias ou crédito recorrente (checkout hospedado, só CREDIT_CARD)."
step "Contrata mensal com cartão. Primeiro período só depois de PAYMENT_CONFIRMED + GET /v3/payments/{id}."
step "Cancela renovação: período já pago mantém-se; não há carência extra se a renovação falhar."
pause "Mensal no cartão confirmado?"

stage "Timeout / REVIEW_REQUIRED (#80)"
say "Resposta ambígua do checkout → REVIEW_REQUIRED. UI: «Estamos confirmando seu checkout»."
step "Os testes automatizados já cobrem o 503 e o bloqueio de nova criação."
step "Não faças retry cego no dashboard Asaas. Runbook: docs/billing/payments.md"
pause "Percebi: incerto = espera webhook ou suporte, nunca segunda cobrança?"

stage "Estorno (#78)"
say "Sandbox: POST /v3/payments/{id}/refund em cobrança CONFIRMED/RECEIVED. Evento PAYMENT_REFUNDED."
open_url "https://docs.asaas.com/recipes/estorno-de-cobranças-em-sandbox"
step "Estorna o pacote de cartão logo após o pagamento (TID partilhado no Sandbox)."
step "Prospectly: reversão auditável; créditos já gastos podem ficar saldo negativo."
pause "PAYMENT_REFUNDED processado sem duplicar a reversão?"

stage "Chargeback (#78)"
say "Sandbox lista chargeback como testável. Disputa pode exigir o time de sucesso Asaas."
open_url "https://docs.asaas.com/docs/chargeback"
open_url "https://docs.asaas.com/docs/what-can-be-tested"
step "Num pagamento de cartão CONFIRMED, dispara chargeback no Sandbox se a UI/API o permitir."
step "Prospectly trata PAYMENT_CHARGEBACK* confirmado: revoga acesso mensal / reverte pacote."
step "Se a conta Sandbox não tiver a acção, pára e pede ajuda Asaas — não habilites produção."
pause "Chargeback observado ou restrição Sandbox anotada?"

warn "Produção (api.asaas.com) continua a exigir autorização explícita e smoke financeiro controlado."
pause "Homologação Sandbox deste wizard concluída (sem produção)?"

finish
