-- AlterTable
ALTER TABLE "LeadScore" ADD COLUMN IF NOT EXISTS "fit" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "LeadScore" ADD COLUMN IF NOT EXISTS "opportunity" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "LeadScore" ADD COLUMN IF NOT EXISTS "engagement" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "LeadScore" ADD COLUMN IF NOT EXISTS "missingData" JSONB NOT NULL DEFAULT '[]';
ALTER TABLE "LeadScore" ADD COLUMN IF NOT EXISTS "recommendedAction" TEXT;
